---
- name: Add postgresql repository key
  apt_key:
    url: http://www.postgresql.org/media/keys/ACCC4CF8.asc
    validate_certs: false

- name: Add postgresql repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    update_cache: yes

- name: Install PostgreSQL
  package:
    name: "{{ package }}"
  loop_control:
    loop_var: package
  with_items:
    - postgresql

- name: Install python-psycopg2
  package:
    name: python-psycopg2
  when: postgresql_install_python_psycopg2
