---
- name: Add Grafana repository key
  apt_key:
    url: https://packagecloud.io/gpg.key

- name: Add Grafana repository
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian/ stretch main
    update_cache: yes

- name: Install Grafana
  package:
    pkg: "{{ item }}"
  with_items:
    - grafana
