---
- hosts: "{{ hostname }}"
  gather_facts: no
  pre_tasks:
    - block:
        - setup:
      rescue:
        - name: Install python-minimal package
          raw: apt-get update -y && apt-get install -y python-minimal

        - setup:
