---
- hosts: lxc.example.com
  vars:
    container_name: rundeck.example.com
    container_group: devops
    container_mac: 00:11:22:33:44:55
  roles:
    - lxc-create


- hosts: rundeck.example.com
  roles:
    - rundeck
