---
- name: Install apt-cacher-ng
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - apt-cacher-ng

- name: Enable PassThrough for HTTPS
  lineinfile:
    line: "PassThroughPattern: .*"
    dest: /etc/apt-cacher-ng/acng.conf
  when: apt_cacher_passthrough
  notify: service apt-cacher-ng restart
