---
- name: Preconfigure mysql-server package
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { name: "mysql-server-{{ mysql_server_version }}", question: "mysql-server/root_password", value: "{{ mysql_server_root_password }}", vtype: "password" }
    - { name: "mysql-server-{{ mysql_server_version }}", question: "mysql-server/root_password_again", value: "{{ mysql_server_root_password }}", vtype: "password" }
  changed_when: false

- include: "{{ item }}"
  with_first_found:
   - "{{ role_path }}/tasks/dist/{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
   - "{{ role_path }}/tasks/dist/{{ ansible_distribution|lower }}.yml"
   - "{{ role_path }}/tasks/dist/main.yml"

- name: Install python-mysqldb package
  package:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python-mysqldb
  when: mysql_server_install_mysqldb == true
