---
- name: Install required packages
  package:
    name:
      - apt-transport-https
      - default-jre

- name: Add rundeck repository key
  apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray

- name: Add rundeck repository
  apt_repository:
    repo: deb https://rundeck.bintray.com/rundeck-deb /
    update_cache: yes

- name: Install rundeck package
  apt:
    name:
      - rundeck

- name: Install rundeck package
  apt:
    name:
      - rundeck-cli
  when: rundeck_install_cli

- name: Configure rundeck webserver
  ini_file:
    dest: /etc/rundeck/rundeck-config.properties
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  with_items:
    - { section: , option: grails.serverURL, value: "http://{{ inventory_hostname }}:80" }
  notify: service rundeck restart

- name: Configure rundeck email
  ini_file:
    dest: /etc/rundeck/rundeck-config.properties
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  with_items:
    - { section: , option: grails.mail.host, value: "{{ smtp_host }}" }
    - { section: , option: grails.mail.port, value: "{{ smtp_port }}" }
    - { section: , option: grails.mail.username, value: "{{ smtp_user }}" }
    - { section: , option: grails.mail.password, value: "{{ smtp_password }}" }
  notify: service rundeck restart
  when: smtp_host is defined

- name: Ensure /var/lib/rundeck belongs to user rundeck
  file:
    path: /var/lib/rundeck
    owner: rundeck
    group: rundeck

- name: Enable rundeck service
  service:
    name: rundeckd
    enabled: yes
    state: started

- name: Generate SSH key for user rundeck
  user:
    name: rundeck
    generate_ssh_key: yes
    ssh_key_comment: rundeck@{{ inventory_hostname }}

- name: Install rundeck ansible-plugin
  get_url:
    url: https://github.com/Batix/rundeck-ansible-plugin/releases/download/2.4.1/ansible-plugin-2.4.1.jar
    dest: /var/lib/rundeck/libext/ansible-plugin-2.4.1.jar
  when: rundeck_install_ansible_plugin
