---
- name: lxc container start
  lxc_container:
    name: "{{ container_name }}"
    state: started

- name: lxc container stop
  lxc_container:
    name: "{{ container_name }}"
    state: stopped

- name: lxc container restart
  lxc_container:
    name: "{{ container_name }}"
    state: restarted
  notify: lxc container wait

- name: lxc container wait
  wait_for:
    host: "{{ container_name }}"
    port: 22
    timeout: 60
    state: started
