---
- name: Enable multiverse repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse
    update_cache: yes
    filename: /etc/apt/sources.list

- name: Add polo repository
  apt_repository:
    repo: ppa:teejee2008/ppa
    update_cache: yes

- name: Install polo package
  package:
    name: polo-file-manager
