---
# https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-ubuntu

- name: Install required packages
  package:
    name: "{{ package }}"
  loop_control:
    loop_var: package
  with_items:
    - software-properties-common

- name: Add Ansible repository
  apt_repository:
    repo: ppa:ansible/ansible
    update_cache: yes

- name: Install Ansible package
  package:
    name: "{{ package }}"
  loop_control:
    loop_var: package
  with_items:
    - ansible
