---
- name: Install required packages
  package:
    name: "{{ item }}"
  with_items:
    - libapache2-mod-php
    - php-mysql

- name: Create DB schema
  mysql_db:
    name: "{{ db_name }}"

- name: Create DB user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "{{ db_name }}.*:ALL"
