---
- include: "{{ item }}"
  with_first_found:
   - install-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml
   - install-{{ ansible_distribution|lower }}.yml
   - install.yml

- name: Accept Java license
  debconf:
    name: "oracle-java{{ jdk_version }}-installer"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: "select"

- name: Disable APT Proxy for download.oracle.com
  lineinfile:
    line: 'Acquire::HTTP::Proxy::download.oracle.com "DIRECT";'
    dest: /etc/apt/apt.conf.d/99_oracle
    create: yes

- name: Install Java JDK
  package:
    name: "{{ item }}"
  with_items:
    - oracle-java{{ jdk_version }}-installer
    - oracle-java{{ jdk_version }}-set-default
