---
- name: Disable USE_LXC_BRIDGE
  replace:
    dest: /etc/default/lxc-net
    regexp: '^USE_LXC_BRIDGE="true"$'
    replace: 'USE_LXC_BRIDGE="false"'

- name: Create network bridge br0
  replace:
    dest: /etc/network/interfaces
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: '^auto eth0$', replace: 'auto br0' }
    - { regexp: '^iface eth0 inet dhcp$', replace: 'iface br0 inet dhcp\n  bridge_ports eth0' }

- name: Configure br0 as default bridge for container
  ini_file:
    dest: /etc/lxc/default.conf
    section: ""
    option: lxc.network.link
    value: br0

- name: Restart network interfaces
  shell: "ip link delete eth0; sleep 3; ifdown --exclude=lo -a; sleep 3; ifup --exclude=lo -a"
  notify: lxc-net restart
