---
- name: Download ius-release.rpm repository package
  get_url:
    url: https://centos7.iuscommunity.org/ius-release.rpm
    dest: /tmp/ius-release.rpm

- name: Install ius-release.rpm package
  yum:
    name: /tmp/ius-release.rpm
    update_cache: yes

- name: Install PHP 5.6
  yum:
    name: php56u
