---
- include: "{{ item }}"
  with_first_found:
   - install-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}-php{{ php_version }}.yml
   - install-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml
   - install-{{ ansible_distribution|lower }}.yml
   - install.yml
