---
# https://docs.gitlab.com/runner/install/linux-repository.html

- name: Install required packages
  package:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    # - debian-archive-keyring

- name: Add GitLab repository key
  apt_key:
    url: https://packages.gitlab.com/runner/gitlab-runner/gpgkey

# https://packages.gitlab.com/install/repositories/runner/gitlab-runner/config_file.list?os=${os}&dist=${dist}&source=script
- name: Add GitLab repository
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items:
    - deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ {{ ansible_distribution_release }} main
    - deb-src https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ {{ ansible_distribution_release }} main

- name: Install GitLab
  package:
    name: "{{ item }}"
  with_items:
    - gitlab-runner
