---
- name: Disable PasswordAuthentication
  replace:
    dest: /etc/ssh/sshd_config
    regexp: "^[#]*PasswordAuthentication(.*)$"
    replace: "PasswordAuthentication no"
  notify: sshd restart

- name: Disable UsePAM
  replace:
    dest: /etc/ssh/sshd_config
    regexp: "^[#]*UsePAM(.*)$"
    replace: "UsePAM no"
  notify: sshd restart

- name: Configure PermitRootLogin
  replace:
    dest: /etc/ssh/sshd_config
    regexp: "^[#]*PermitRootLogin(.*)$"
    replace: "PermitRootLogin without-password"
  notify: sshd restart
